"""
LegalDoc — generated by Qwentin Site Factory v2.0
Developed by cjbwebdevelopment.com
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

def _env(key, default=""):
    return os.environ.get(key, default)

SECRET_KEY = _env("SECRET_KEY", "django-insecure-fallback-CHANGE-IN-PRODUCTION")
DEBUG = _env("DEBUG", "True").lower() == "true"

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ALLOWED_HOSTS = ["legaldoc.site", "www.legaldoc.site", "*", "localhost", "127.0.0.1"]
_eh = _env("ALLOWED_HOSTS", "")
if _eh:
    ALLOWED_HOSTS.extend([h.strip() for h in _eh.split(",") if h.strip()])

CSRF_TRUSTED_ORIGINS = ["https://legaldoc.site", "https://www.legaldoc.site"]
_eo = _env("CSRF_TRUSTED_ORIGINS", "")
if _eo:
    CSRF_TRUSTED_ORIGINS.extend([o.strip() for o in _eo.split(",") if o.strip()])

INSTALLED_APPS = ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'users', 'billing', 'dashboard']

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

# Database
_db = _env("DATABASE_URL", "")
if _db and "railway.internal" in _db:
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}}
elif _db and _db.startswith("postgres"):
    import dj_database_url
    DATABASES = {"default": dj_database_url.config(default=_db, conn_max_age=600)}
else:
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-gb"
TIME_ZONE = "Europe/London"
USE_I18N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

TEMPLATES = [{
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [BASE_DIR / "templates"],
    "APP_DIRS": True,
    "OPTIONS": {
        "context_processors": [
            "django.template.context_processors.debug",
            "django.template.context_processors.request",
            "django.contrib.auth.context_processors.auth",
            "django.contrib.messages.context_processors.messages",
        ],
    },
}]

BRANDING = "Developed by cjbwebdevelopment.com"

STRIPE_SECRET_KEY = _env('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = _env('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = _env('STRIPE_WEBHOOK_SECRET', '')

DEFAULT_FROM_EMAIL = _env("MAIL_FROM", "noreply@legaldoc.site")
EMAIL_HOST = _env("MAIL_HOST", "smtp.gmail.com")
EMAIL_HOST_USER = _env("MAIL_USER", "support@cjbwebdevelopment.com")
EMAIL_HOST_PASSWORD = _env("MAIL_PASSWORD", "")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
SERVER_EMAIL = DEFAULT_FROM_EMAIL
